# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_pandas_gui(object):
    def setupUi(self, pandas_gui):
        pandas_gui.setObjectName("pandas_gui")
        pandas_gui.resize(1026, 675)
        font = QtGui.QFont()
        font.setPointSize(8)
        pandas_gui.setFont(font)
        self.centralWidget = QtWidgets.QWidget(pandas_gui)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_addtolist = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_addtolist.sizePolicy().hasHeightForWidth())
        self.pb_addtolist.setSizePolicy(sizePolicy)
        self.pb_addtolist.setMinimumSize(QtCore.QSize(370, 0))
        self.pb_addtolist.setObjectName("pb_addtolist")
        self.gridLayout.addWidget(self.pb_addtolist, 12, 0, 1, 1)
        self.cbb_keyword_ls = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_keyword_ls.sizePolicy().hasHeightForWidth())
        self.cbb_keyword_ls.setSizePolicy(sizePolicy)
        self.cbb_keyword_ls.setMinimumSize(QtCore.QSize(370, 0))
        self.cbb_keyword_ls.setObjectName("cbb_keyword_ls")
        self.gridLayout.addWidget(self.cbb_keyword_ls, 9, 0, 1, 1)
        self.cbb_keyword = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_keyword.sizePolicy().hasHeightForWidth())
        self.cbb_keyword.setSizePolicy(sizePolicy)
        self.cbb_keyword.setMinimumSize(QtCore.QSize(370, 0))
        self.cbb_keyword.setEditable(False)
        self.cbb_keyword.setObjectName("cbb_keyword")
        self.gridLayout.addWidget(self.cbb_keyword, 2, 0, 1, 1)
        self.pb_run = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_run.sizePolicy().hasHeightForWidth())
        self.pb_run.setSizePolicy(sizePolicy)
        self.pb_run.setMinimumSize(QtCore.QSize(100, 0))
        self.pb_run.setObjectName("pb_run")
        self.gridLayout.addWidget(self.pb_run, 12, 2, 1, 1)
        self.cbb_condition = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_condition.sizePolicy().hasHeightForWidth())
        self.cbb_condition.setSizePolicy(sizePolicy)
        self.cbb_condition.setMinimumSize(QtCore.QSize(370, 0))
        self.cbb_condition.setObjectName("cbb_condition")
        self.gridLayout.addWidget(self.cbb_condition, 3, 0, 1, 1)
        self.listw_listcommand = QtWidgets.QListWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listw_listcommand.sizePolicy().hasHeightForWidth())
        self.listw_listcommand.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listw_listcommand.setFont(font)
        self.listw_listcommand.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listw_listcommand.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listw_listcommand.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.listw_listcommand.setTextElideMode(QtCore.Qt.ElideNone)
        self.listw_listcommand.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listw_listcommand.setObjectName("listw_listcommand")
        self.gridLayout.addWidget(self.listw_listcommand, 1, 1, 9, 2)
        self.cbb_criteria = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_criteria.sizePolicy().hasHeightForWidth())
        self.cbb_criteria.setSizePolicy(sizePolicy)
        self.cbb_criteria.setMinimumSize(QtCore.QSize(370, 0))
        self.cbb_criteria.setEditable(True)
        self.cbb_criteria.setObjectName("cbb_criteria")
        self.gridLayout.addWidget(self.cbb_criteria, 4, 0, 1, 1)
        self.cbb_condition2next = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_condition2next.sizePolicy().hasHeightForWidth())
        self.cbb_condition2next.setSizePolicy(sizePolicy)
        self.cbb_condition2next.setMinimumSize(QtCore.QSize(370, 0))
        self.cbb_condition2next.setObjectName("cbb_condition2next")
        self.gridLayout.addWidget(self.cbb_condition2next, 1, 0, 1, 1)
        self.pb_clear_all_comm = QtWidgets.QPushButton(self.centralWidget)
        self.pb_clear_all_comm.setObjectName("pb_clear_all_comm")
        self.gridLayout.addWidget(self.pb_clear_all_comm, 12, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rb_nhead = QtWidgets.QRadioButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_nhead.sizePolicy().hasHeightForWidth())
        self.rb_nhead.setSizePolicy(sizePolicy)
        self.rb_nhead.setObjectName("rb_nhead")
        self.horizontalLayout_2.addWidget(self.rb_nhead)
        self.rb_ntail = QtWidgets.QRadioButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_ntail.sizePolicy().hasHeightForWidth())
        self.rb_ntail.setSizePolicy(sizePolicy)
        self.rb_ntail.setObjectName("rb_ntail")
        self.horizontalLayout_2.addWidget(self.rb_ntail)
        self.rb_nlarge = QtWidgets.QRadioButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_nlarge.sizePolicy().hasHeightForWidth())
        self.rb_nlarge.setSizePolicy(sizePolicy)
        self.rb_nlarge.setObjectName("rb_nlarge")
        self.horizontalLayout_2.addWidget(self.rb_nlarge)
        self.rb_nsmall = QtWidgets.QRadioButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_nsmall.sizePolicy().hasHeightForWidth())
        self.rb_nsmall.setSizePolicy(sizePolicy)
        self.rb_nsmall.setObjectName("rb_nsmall")
        self.horizontalLayout_2.addWidget(self.rb_nsmall)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.cbb_number = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbb_number.sizePolicy().hasHeightForWidth())
        self.cbb_number.setSizePolicy(sizePolicy)
        self.cbb_number.setMinimumSize(QtCore.QSize(370, 0))
        self.cbb_number.setEditable(True)
        self.cbb_number.setObjectName("cbb_number")
        self.gridLayout.addWidget(self.cbb_number, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 13, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.le_command = QtWidgets.QLineEdit(self.centralWidget)
        self.le_command.setObjectName("le_command")
        self.gridLayout.addWidget(self.le_command, 11, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 10, 1, 1, 1)
        self.tablev_output = QtWidgets.QTableView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablev_output.sizePolicy().hasHeightForWidth())
        self.tablev_output.setSizePolicy(sizePolicy)
        self.tablev_output.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tablev_output.setFont(font)
        self.tablev_output.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tablev_output.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tablev_output.setObjectName("tablev_output")
        self.gridLayout.addWidget(self.tablev_output, 14, 0, 1, 3)
        pandas_gui.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(pandas_gui)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1026, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuImport = QtWidgets.QMenu(self.menuFile)
        self.menuImport.setObjectName("menuImport")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuALLExport = QtWidgets.QMenu(self.menuExport)
        self.menuALLExport.setObjectName("menuALLExport")
        self.menuResExport = QtWidgets.QMenu(self.menuExport)
        self.menuResExport.setObjectName("menuResExport")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuSummary = QtWidgets.QMenu(self.menuBar)
        self.menuSummary.setObjectName("menuSummary")
        pandas_gui.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(pandas_gui)
        self.statusBar.setObjectName("statusBar")
        pandas_gui.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(pandas_gui)
        self.toolBar.setObjectName("toolBar")
        pandas_gui.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(pandas_gui)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(pandas_gui)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/fileclose.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon1)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(pandas_gui)
        self.actionExit.setObjectName("actionExit")
        self.actionDATA_MINER_0_1 = QtWidgets.QAction(pandas_gui)
        self.actionDATA_MINER_0_1.setObjectName("actionDATA_MINER_0_1")
        self.actionCSV_import = QtWidgets.QAction(pandas_gui)
        self.actionCSV_import.setObjectName("actionCSV_import")
        self.actionData_Summary = QtWidgets.QAction(pandas_gui)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/cfg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionData_Summary.setIcon(icon2)
        self.actionData_Summary.setObjectName("actionData_Summary")
        self.actionCSV_ALL_export = QtWidgets.QAction(pandas_gui)
        self.actionCSV_ALL_export.setObjectName("actionCSV_ALL_export")
        self.actionCSV_Result_export = QtWidgets.QAction(pandas_gui)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/tsave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCSV_Result_export.setIcon(icon3)
        self.actionCSV_Result_export.setObjectName("actionCSV_Result_export")
        self.menuImport.addAction(self.actionCSV_import)
        self.menuALLExport.addAction(self.actionCSV_ALL_export)
        self.menuResExport.addAction(self.actionCSV_Result_export)
        self.menuExport.addAction(self.menuALLExport.menuAction())
        self.menuExport.addAction(self.menuResExport.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionDATA_MINER_0_1)
        self.menuSummary.addAction(self.actionData_Summary)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSummary.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionData_Summary)
        self.toolBar.addAction(self.actionCSV_Result_export)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCSV_import)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClose)

        self.retranslateUi(pandas_gui)
        QtCore.QMetaObject.connectSlotsByName(pandas_gui)

    def retranslateUi(self, pandas_gui):
        _translate = QtCore.QCoreApplication.translate
        pandas_gui.setWindowTitle(_translate("pandas_gui", "pandas_gui"))
        self.pb_addtolist.setToolTip(_translate("pandas_gui", "Add command to Command Selection List"))
        self.pb_addtolist.setText(_translate("pandas_gui", "Add Command to Selection List"))
        self.cbb_keyword_ls.setToolTip(_translate("pandas_gui", "Select column keyword for sorting order in Result Output"))
        self.cbb_keyword.setToolTip(_translate("pandas_gui", "Select column Keyword"))
        self.pb_run.setToolTip(_translate("pandas_gui", "Run selected command in the selection list"))
        self.pb_run.setText(_translate("pandas_gui", "Run Selected Command"))
        self.cbb_condition.setToolTip(_translate("pandas_gui", "Select conditions for column keyword"))
        self.cbb_criteria.setToolTip(_translate("pandas_gui", "Select criteria for selected column keyword"))
        self.cbb_condition2next.setToolTip(_translate("pandas_gui", "Select & (AND), | (OR) to combine two conditions"))
        self.pb_clear_all_comm.setToolTip(_translate("pandas_gui", "Clear all commands in selection list"))
        self.pb_clear_all_comm.setText(_translate("pandas_gui", "Clear All Commands"))
        self.label.setText(_translate("pandas_gui", "N: Rows to display in Result Output"))
        self.rb_nhead.setToolTip(_translate("pandas_gui", "Display N row from the first row"))
        self.rb_nhead.setText(_translate("pandas_gui", "N Head"))
        self.rb_ntail.setToolTip(_translate("pandas_gui", "Display N rows from the last row"))
        self.rb_ntail.setText(_translate("pandas_gui", "N Tail"))
        self.rb_nlarge.setToolTip(_translate("pandas_gui", "Display  N largest rows in selected column"))
        self.rb_nlarge.setText(_translate("pandas_gui", "N Largest"))
        self.rb_nsmall.setToolTip(_translate("pandas_gui", "Display N smallest rows in selected column"))
        self.rb_nsmall.setText(_translate("pandas_gui", "N Smallest"))
        self.label_2.setText(_translate("pandas_gui", "Command Selection List"))
        self.cbb_number.setToolTip(_translate("pandas_gui", "Select number of rows to display in Result Output"))
        self.label_4.setText(_translate("pandas_gui", "Result Output"))
        self.label_3.setText(_translate("pandas_gui", "Command"))
        self.label_5.setText(_translate("pandas_gui", "Command Edit"))
        self.menuFile.setTitle(_translate("pandas_gui", "File"))
        self.menuImport.setTitle(_translate("pandas_gui", "Import"))
        self.menuExport.setTitle(_translate("pandas_gui", "Export"))
        self.menuALLExport.setTitle(_translate("pandas_gui", "Input"))
        self.menuResExport.setTitle(_translate("pandas_gui", "Result"))
        self.menuAbout.setTitle(_translate("pandas_gui", "About"))
        self.menuSummary.setTitle(_translate("pandas_gui", "Summary"))
        self.toolBar.setWindowTitle(_translate("pandas_gui", "toolBar"))
        self.actionOpen.setText(_translate("pandas_gui", "Open"))
        self.actionOpen.setToolTip(_translate("pandas_gui", "Open HDF5 File"))
        self.actionClose.setText(_translate("pandas_gui", "Close"))
        self.actionExit.setText(_translate("pandas_gui", "Exit"))
        self.actionDATA_MINER_0_1.setText(_translate("pandas_gui", "DataViewer"))
        self.actionCSV_import.setText(_translate("pandas_gui", "CSV"))
        self.actionCSV_import.setToolTip(_translate("pandas_gui", "Import CSV file"))
        self.actionData_Summary.setText(_translate("pandas_gui", "Data Summary"))
        self.actionCSV_ALL_export.setText(_translate("pandas_gui", "CSV Input"))
        self.actionCSV_ALL_export.setToolTip(_translate("pandas_gui", "CSV Input Export"))
        self.actionCSV_Result_export.setText(_translate("pandas_gui", "CSV Result"))
        self.actionCSV_Result_export.setToolTip(_translate("pandas_gui", "CSV Result Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pandas_gui = QtWidgets.QMainWindow()
    ui = Ui_pandas_gui()
    ui.setupUi(pandas_gui)
    pandas_gui.show()
    sys.exit(app.exec_())

